"""initial

Revision ID: 7ffa228f6e47
Revises: 
Create Date: 2026-02-16 16:02:21.221761+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ffa228f6e47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'access_logs',
        sa.Column(
            'is_anomalous',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )
    op.alter_column('access_logs', 'is_anomalous', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_logs', 'is_anomalous')
    # ### end Alembic commands ###
