"""add_processing_status

Revision ID: 9a7fac3fbd83
Revises: 70cad4e8c79c
Create Date: 2026-04-17 07:09:26.477148+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7fac3fbd83'
down_revision = '70cad4e8c79c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('processing_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'processing_status')
    # ### end Alembic commands ###
