"""fix_is_anomalous_default

Revision ID: 9c07182102fb
Revises: 7ffa228f6e47
Create Date: 2026-03-21 04:17:41.547550+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c07182102fb'
down_revision = '7ffa228f6e47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
